# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    groups:
      majors:
        update-types: [ "major" ]
      minors-and-patches:
        update-types: [ "minor", "patch" ]
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories: "**/*"
    groups:
      majors:
        update-types: [ "major" ]
      minors-and-patches:
        update-types: [ "minor", "patch" ]
    schedule:
      interval: "weekly"
