site_name: UFW Documentation

site_url: https://github.com/TommyPersson/ufw/
repo_url: https://github.com/TommyPersson/ufw/
repo_name: TommyPersson/ufw
edit_uri: edit/main/documentation/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TommyPersson/ufw/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.footer
    - toc.follow
    - content.action.edit
    - content.action.view
  icon:
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - awesome-pages

extra_css:
  - stylesheets/extra.css